input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  if [event] == "login_failed" {
    metrics {
      meter => [ "failed_logins_%{ip}" ]
      add_tag => "metric_check"
      flush_interval => 5
      clear_interval => 10
    }
  }
}

output {
  # This sends ALL logs to the main index
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "security-logs-%{+YYYY.MM.dd}"
  }
  
  # This creates an Alert if a single IP hits 5+ times
  if "metric_check" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "security-alerts-%{+YYYY.MM.dd}"
    }
  }
}